=== enterstudio/denaturalized/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "id": "https://github.com/jebeck/denaturalized",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "reason": {
        "type": "string"
      },
      "reasonCategory": {
        "type": "string",
        "enum": [
          "Hiding World War II crimes or association with Nazis",
          "Serious crimes, suspicion of spying for the communists, or association with terrorists",
          "All other reasons"
        ]
      },
      "denaturalizationYear": {
        "type": "number",
        "minimum": 1776,
        "maximum": 2016
      },
      "status": {
        "type": "string"
      }
    },
    "additionalProperties": false,
    "required": [
      "name",
      "reason",
      "reasonCategory",
      "denaturalizationYear"
    ]
  }
}

=== enterstudio/denaturalized/united-states.json
[
 {
   "name": "Ibraheem Adeneye",
   "reason": "Convicted of conspiracy to commit marriage fraud, marriage fraud, naturalization fraud, and making a false statement to a federal agency. Adeneye indicated that he was engaged in brokering sham marriages between Nigerian nationals and U.S. citizens so that the Nigerians could obtain immigration benefits, ultimately leading to U.S. citizenship. In return, the U.S. citizen \"spouses\" received cash payments to assist the Nigerians in the deception.",
   "reasonCategory": "All other reasons",
   "denaturalizationYear": 2010,
   "status": "U.S. District Judge Kenneth Hoyt sentenced Adeneye to the time he has already served in prison. The judge granted the government's motion to strip Adeneye of his U.S. citizenship. Adeneye became an alien subject to removal from the United States to Nigeria."
 },
 {
   "name": "Solomon Adler",
   "reason": "Government economist under investigation as a communist spy. Moved to Britain and was denaturalized after his passport expired.",
   "reasonCategory": "Serious crimes, suspicion of spying for the communists, or association with terrorists",
   "denaturalizationYear": 1952,
   "status": "Renewed American citizenship when Sino-American diplomatic relations were reestablished in 1971."
 },
 {
   "name": "Rasmi Khader Almallah",
   "reason": "Became a permanent resident via a 1981 marriage four days before his student visa expired (later deemed \"a green card marriage\" by the Immigration and Naturalization Service) and naturalized in 1988. Almallah was stripped of his United States citizenship after coming to the authorities' attention for his connection to the Holy Land Foundation (adjudged to be a Hamas fundraising entity) and also as a former employer of one of the 9/11 bombers.",
   "reasonCategory": "Serious crimes, suspicion of spying for the communists, or association with terrorists",
   "denaturalizationYear": 2007,
   "status": "Appealed unsuccessfully to the United States Court of Appeals, Fifth Circuit. Resident of Jordan, where he is a member of the Jordanian Senate."
 },
 {
   "name": "Basil Artishenko",
   "reason": "Member of Nazi-controlled police in Khoiniki (present-day Chojniki, Belarus), accused of helping execute about 100 unarmed people.",
   "reasonCategory": "Hiding World War II crimes or association with Nazis",
   "denaturalizationYear": 1984,
   "status": "Not deported from the United States in a settlement with the government that required him to give up his citizenship and nationality in 1984; died in 1989."
 },
 {
   "name": "Andrija Artukovič",
   "reason": "Croatian Minister of Interior 1941-1942; 1943.",
   "reasonCategory": "Hiding World War II crimes or association with Nazis",
   "denaturalizationYear": 1986,
   "status": "Yugoslavkia requested extradition 1951; request rejected 1959; deported 1986 to Yugoslavkia died in prison 1988"
 },
 {
   "name": "Jan Awdziej",
   "reason": "Mayor of Stolpce in Nazi-occupied Poland.",
   "reasonCategory": "Hiding World War II crimes or association with Nazis",
   "denaturalizationYear": 1984,
   "status": "Left the country in February 1984 for West Germany, where he renounced his U.S. citizenship as part of a deal to avoid prosecution. Died in 1998."
 },
 {
   "name": "Martin Bartesch",
   "reason": "Failure to disclose his past when he applied for U.S. citizenship: member of the Prinz Eugen Division of the S.S. from 1943–44; while a guard at Mauthausen concentration camp, he shot Gottfried Ochshorn dead when Ochshorn attempted to escape.",
   "reasonCategory": "Hiding World War II crimes or association with Nazis",
   "denaturalizationYear": 1987,
   "status": "Fled to Austria, where he later died."
 },
 {
   "name": "Anton Baumann",
   "reason": "SS Death Head's Battalion guard at Stutthof and Buchenwald concentration camps.",
   "reasonCategory": "Hiding World War II crimes or association with Nazis",
   "denaturalizationYear": 1991,
   "status": "Ordered deported to Germany in 1993, but deportation was never carried out due to his health; died in 1994."
 },
 {
   "name": "Aldo Mario Bellei",
   "reason": "Born in Italy to an Italian father and an American mother, Bellei lost his citizenship for not moving to and living in the United States for at least five years prior to his 28th birthday; see Rogers v. Bellei.",
   "reasonCategory": "All other reasons",
   "denaturalizationYear": 1971,
   "status": "U.S. Supreme Court vacated lower court ruling, finding against Bellei in 1971. Provision under which Bellei was denaturalized was repealed (Public Law 95-432) by Congress in 1978."
 },
 {
   "name": "Wolodymyr Berezowskyj",
   "reason": "Guard at Trawniki, Poniatowa, and Gusen concentration camps.",
   "reasonCategory": "Hiding World War II crimes or association with Nazis",
   "denaturalizationYear": 1998,
   "status": "Never deported from the United States due to his health; died in 2010."
 },
 {
   "name": "Petras Bernotavičius",
   "reason": "Deputy to Nazi-appointed mayor and police commander Werner Loew in Kupiškis, Lithuania.",
   "reasonCategory": "Hiding World War II crimes or association with Nazis",
   "denaturalizationYear": 2002,
   "status": "Fled to Lithuania in 2002, where he later died."
 },
 {
   "name": "Anton Bless",
   "reason": "SS-Death's Head Battalion guard at Auschwitz concentration camp.",
   "reasonCategory": "Hiding World War II crimes or association with Nazis",
   "denaturalizationYear": 1992,
   "status": "Fled to Germany in 1992, where he died in 2004."
 },
 {
   "name": "Hermine Braunsteiner",
   "reason": "Failure to disclose conviction for war crimes; female concentration camp guard.",
   "reasonCategory": "Hiding World War II crimes or association with Nazis",
   "denaturalizationYear": 1971,
   "status": "First Nazi war criminal extradited from the United States to Germany. Sentenced to life imprisonment, but released in 1996 for health reasons."
 },
 {
   "name": "Ildefonsas Bučmys",
   "reason": "Guard at Majdanek concentration camp.",
   "reasonCategory": "Hiding World War II crimes or association with Nazis",
   "denaturalizationYear": 2005,
   "status": "Not deported from the United States in a settlement with the government that required him to give up his U.S. citizenship and nationality in 2005; he died later that same year."
 },
 {
   "name": "Juozas Budreika",
   "reason": "Member of the Lithuanian Schutzmannschaft.",
   "reasonCategory": "Hiding World War II crimes or association with Nazis",
   "denaturalizationYear": 1996,
   "status": "Fled to Lithuania on May 14, 1996 in an agreement with the OSI. Died less than a month after arriving in Lithuania."
 },
 {
   "name": "Kazys Čiurinskas",
   "reason": "Member of the Lithuanian Schutzmannschaft.",
   "reasonCategory": "Hiding World War II crimes or association with Nazis",
   "denaturalizationYear": 1997,
   "status": "Fled to Lithuania in 1999 after consenting to deportation."
 },
 {
   "name": "Algimantas Dailidė",
   "reason": "For having \"illegally procured\" citizenship. Member of the Lithuanian Security Police during World War II.",
   "reasonCategory": "Hiding World War II crimes or association with Nazis",
   "denaturalizationYear": 1997,
   "status": "Fled to Germany in 2004 after being ordered deported. Convicted by a Lithuanian court in 2006, but not imprisoned due to his age. Still lives in Germany."
 },
 {
   "name": "Damrah, Fawaz Mohammed",
   "reason": "Imam who was convicted on June 18, 2004 of lying on his naturalization application about his association with three groups classified as terrorist organizations by the U.S. government.",
   "reasonCategory": "Serious crimes, suspicion of spying for the communists, or association with terrorists",
   "denaturalizationYear": 2004,
   "status": "Deported to the Palestinian West Bank in January 2007."
 },
 {
   "name": "John Demjanjuk",
   "reason": "Allegedly concealed being a concentration camp guard at Sobibor, Majdanek, Flossenbürg, and Trawniki, thus committing naturalization fraud.",
   "reasonCategory": "Hiding World War II crimes or association with Nazis",
   "denaturalizationYear": 2002,
   "status": "Deported to Germany. On July 13, 2009, Demjanjuk was formally charged with 28,060 counts of accessory to murder, one for each person who died at Sobibor during the time he was accused of serving as a guard at the Nazi death camp. On November 30, 2009, Demjanjuk's trial began in Munich. Convicted by Germany in 2011, but released from custody pending his appeal. Died in 2012 before appeal could be heard, thus the Munich District court declared him \"presumed innocent\". The court confirmed that, in accordance with German law, Demjanjuk's previous interim conviction had been invalidated and that Demjanjuk was without a criminal record."
 },
 {
   "name": "Jakob Frank Denzinger",
   "reason": "Guard at Mauthausen, St. Georgen, Kraków, and Auschwitz concentration camps.",
   "reasonCategory": "Hiding World War II crimes or association with Nazis",
   "denaturalizationYear": 1989,
   "status": "Fled to West Germany in August 1989; living in Croatia as of 2014."
 },
 {
   "name": "Michael Derkacz",
   "reason": "Member of the Ukrainian police who \"assisted the Nazis in persecuting civilian Jews.\"",
   "reasonCategory": "Hiding World War II crimes or association with Nazis",
   "denaturalizationYear": 1982,
   "status": "Derkacz failed to file a notice of appeal against this summary judgment before the time for such an appeal expired, and the revocation of his citizenship thus became final. He died in August 1983 before his deportation hearings were scheduled to begin."
 },
 {
   "name": "Valdis Didrichsons",
   "reason": "Member of Arajs Kommando military unit in Nazi-occupied Latvia.",
   "reasonCategory": "Hiding World War II crimes or association with Nazis",
   "denaturalizationYear": 1990,
   "status": "Never deported from the United States due to his health; died in 1995."
 },
 {
